@startuml
hide circle
skinparam classAttributeIconSize 0
Package "ContactedInfo" <<Rectangle>>{
class ContactedInfo {
+getRecentDate() : RecentDate
+getDescription() : Description
+getDefaultContactedInfo() : ContactedInfo
+isValidContactedInfo(String, String) : boolean
+getDaysPassed() : Integer
}

class Description {
+defaultDesc() : Description
+isValidDescription(String) : boolean
}

class RecentDate {
value: String
+parse(String) : RecentDate
+defaultRecentDate() : RecentDate
}
}

ContactedInfo *-down-> "1 LocalDate" RecentDate
ContactedInfo *-down-> "1 value" Description
@enduml
