@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model

Class UniqueTagList
Class "<<interface>>\nReadOnlyUniqueTagList" as ReadOnlyUniqueTagList

Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Address
Class BirthDate
Class Email
Class Name
Class Phone
Class Tag
Class ContactedInfo
Class Reminder
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model ..> ReadOnlyUniqueTagList
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager --> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueTagList
AddressBook *--> "1" UniquePersonList
UniqueTagList .up.|> ReadOnlyUniqueTagList
UniquePersonList --> "\n\n\n   all\n  ~*" Person
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "       1" BirthDate
Person *--> "1" Address
Person *--> "*" Tag
Person *--> "*" ContactedInfo
Person *--> "*" Reminder

AddressBook -[hidden]left-> ReadOnlyUniqueTagList
Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email


ModelManager -->"filtered   \n           ~*" Person
@enduml
