@startuml
'https://plantuml.com/sequence-diagram

mainframe **sd** Read addressbook.json
hide footbox

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #FFFFFF
    FontName Arial
}
Participant "MainApp" as main
Participant "JsonAddressBookStorage" as storage

main -> storage: readAddressBook()


alt read successfully
storage --> main: JsonSerializableAddressBook
else else
storage -> storage: backup()
end


@enduml
